#!/bin/bash
#quickly unmount external USB drive 
#specifically 'Samsung USB' for music

#list devices with lsblk (use -l arg to remove dir tree character)
#lsblk -- list devices

# Determine dev ID for Samsung SSD (should be sdc1)
devDir=/dev/
devName=$(lsblk -l | grep samsung | awk -F" " '{print $1 }')
devFullname=$devDir$devName
drvFullname=${devFullname::-1}

if [ ${#devName} -gt 0 ];
then
	udisksctl unmount -bf $devFullname
	#umount $devFullname
	sudo udisksctl power-off -b $drvFullname
else
	echo "USB drive not found."
fi

